### ISSUE TITLE
removeDuplicates example operates on whole model

### ISSUE THREAD

**Issue by mvysny** [ankidroid/apisample#1]
Hello :) In the example code, removeDuplicates() operates on the whole card model and filters out cards which are present anywhere in the model. This however will cause the user to be unable to add same card into multiple decks. This has been filed as Aedict bug at https://github.com/mvysny/aedict/issues/752 .

Please, is there a way for the removeDuplicates() example method to be changed to be scoped on the target deck only, instead of on the whole card model? Thanks!

BR,
Martin

**Comment by timrae** [comment]
See my reply in the other thread
